### ISSUE TITLE
Where is meta.define.event?

### ISSUE THREAD

**Issue by pchaigno** [amclain/sublime-netlinx#8]
This grammar is used to highlight code on GitHub.com. When the compiler tries to compile the `.tmLanguage` file, it fails to include `meta.define.event` (see github/linguist#3924 for further information). Where is this normally defined?

**Comment by amclain** [comment]
Thanks for the report. I have removed the `meta.define.event` include in the `2.1.2` release. I don't see the error anymore in the Sublime console or when running the linguist grammar compiler. This issue appears to be resolved now -- feel free to reopen it if I'm mistaken.

**Comment by pchaigno** [comment]
Thanks!
